import { PLAN_FEATURES } from '@/config/plans'

export const COMPANY_PERMISSIONS = {
  MANAGE_COMPANY: 'manage_company',
  MANAGE_BILLING: 'manage_billing',
  MANAGE_USERS: 'manage_users',
  VIEW_REPORTS: 'view_reports',
  EDIT_PRODUCTS: 'edit_products',
  CREATE_SALES: 'create_sales',
  UPDATE_STOCK: 'update_stock',
  VIEW_PRODUCTS: 'view_products',
  VIEW_CUSTOMERS: 'view_customers',
  CREATE_PURCHASE: 'create_purchase',
} as const

export const COMPANY_FEATURE_KEYS = {
  BASIC_INVENTORY: PLAN_FEATURES.BASIC_INVENTORY,
  BASIC_SALES: PLAN_FEATURES.BASIC_SALES,
  PURCHASE_MODULE: PLAN_FEATURES.PURCHASE_MODULE,
  BASIC_REPORTS: PLAN_FEATURES.BASIC_REPORTS,
  ADVANCED_REPORTS: PLAN_FEATURES.ADVANCED_REPORTS,
  MULTI_BRANCH: PLAN_FEATURES.MULTI_BRANCH,
  AUDIT_LOGS: PLAN_FEATURES.AUDIT_LOGS,
  UNLIMITED_USERS: PLAN_FEATURES.UNLIMITED_USERS,
  TEAM_MANAGEMENT: PLAN_FEATURES.TEAM_MANAGEMENT,
  ADMIN_PANEL: PLAN_FEATURES.ADMIN_PANEL,
  CUSTOM_BRANDING: PLAN_FEATURES.CUSTOM_BRANDING,
} as const

export type CompanyPermissionKey = typeof COMPANY_PERMISSIONS[keyof typeof COMPANY_PERMISSIONS]
export type CompanyFeatureKey = typeof COMPANY_FEATURE_KEYS[keyof typeof COMPANY_FEATURE_KEYS]
