#!/bin/bash
# Setup Redis (Upstash) for rate limiting
# This script helps configure Upstash Redis for distributed rate limiting in production

set -e

echo "🚀 MiPOS Redis Setup Script"
echo "=================================="
echo ""

# Check if .env.local exists
if [ ! -f .env.local ]; then
    echo "❌ Error: .env.local file not found in current directory"
    echo "Please run this script from the project root (where .env.local exists)"
    exit 1
fi

# Check if Redis config already exists
if grep -q "UPSTASH_REDIS_REST_URL" .env.local; then
    echo "ℹ️  Redis configuration already exists in .env.local"
    echo "Skipping setup. To reconfigure, manually update:"
    echo "  - UPSTASH_REDIS_REST_URL"
    echo "  - UPSTASH_REDIS_REST_TOKEN"
    exit 0
fi

echo "This script will help you configure Upstash Redis."
echo ""
echo "Steps:"
echo "1. Go to https://console.upstash.com/"
echo "2. Sign up or log in"
echo "3. Create a new Redis database"
echo "4. Copy the REST API credentials"
echo ""

read -p "Have you created an Upstash Redis database? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Please create a Redis database at https://console.upstash.com/"
    exit 0
fi

echo ""
echo "Enter your Upstash credentials:"
echo ""

read -p "UPSTASH_REDIS_REST_URL: " UPSTASH_URL
read -s -p "UPSTASH_REDIS_REST_TOKEN: " UPSTASH_TOKEN
echo ""

# Validate inputs
if [ -z "$UPSTASH_URL" ] || [ -z "$UPSTASH_TOKEN" ]; then
    echo "❌ Error: Both URL and token are required"
    exit 1
fi

# Test connection
echo ""
echo "Testing connection to Redis..."
RESPONSE=$(curl -s -w "\n%{http_code}" -X GET "$UPSTASH_URL/ping" \
    -H "Authorization: Bearer $UPSTASH_TOKEN")

HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
BODY=$(echo "$RESPONSE" | head -n-1)

if [ "$HTTP_CODE" = "200" ]; then
    echo "✅ Connection successful!"
else
    echo "❌ Connection failed (HTTP $HTTP_CODE)"
    echo "Response: $BODY"
    exit 1
fi

# Append to .env.local
echo ""
echo "Saving credentials to .env.local..."

cat >> .env.local << EOF

# Redis Configuration for Rate Limiting
# Generated by setup-redis.sh
UPSTASH_REDIS_REST_URL=$UPSTASH_URL
UPSTASH_REDIS_REST_TOKEN=$UPSTASH_TOKEN
EOF

echo "✅ Redis configuration saved!"
echo ""
echo "Next steps:"
echo "1. The rate limiter will now use Redis for distributed deployments"
echo "2. In-memory fallback is still active if Redis fails"
echo "3. Test locally: npm run dev"
echo "4. Deploy and verify in production"
echo ""
echo "For more info, see: apps/frontend/src/app/api/auth/register/IMPROVEMENTS.md"
