-- Create business_config table
CREATE TABLE IF NOT EXISTS public.business_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_name TEXT DEFAULT 'Mi Tienda',
    address TEXT,
    phone TEXT,
    email TEXT,
    website TEXT,
    logo_url TEXT,
    tax_rate NUMERIC DEFAULT 10,
    currency TEXT DEFAULT 'PYG',
    receipt_footer TEXT DEFAULT 'Gracias por su compra',
    low_stock_threshold INTEGER DEFAULT 10,
    auto_backup BOOLEAN DEFAULT true,
    backup_frequency TEXT DEFAULT 'daily',
    email_notifications BOOLEAN DEFAULT true,
    sms_notifications BOOLEAN DEFAULT false,
    push_notifications BOOLEAN DEFAULT true,
    timezone TEXT DEFAULT 'America/Asuncion',
    date_format TEXT DEFAULT 'DD/MM/YYYY',
    time_format TEXT DEFAULT '24h',
    decimal_places INTEGER DEFAULT 0,
    enable_barcode_scanner BOOLEAN DEFAULT true,
    enable_receipt_printer BOOLEAN DEFAULT true,
    enable_cash_drawer BOOLEAN DEFAULT true,
    max_discount_percentage NUMERIC DEFAULT 50,
    require_customer_info BOOLEAN DEFAULT false,
    enable_loyalty_program BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.business_config ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Enable read access for all users" ON public.business_config
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON public.business_config
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for admins only" ON public.business_config
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM public.users 
            WHERE users.id = auth.uid() 
            AND users.role = 'ADMIN'
        )
    );

-- Insert default row if not exists
INSERT INTO public.business_config (id, business_name)
VALUES (1, 'Mi Tienda')
ON CONFLICT (id) DO NOTHING;
